# This is a basic workflow to help you get started with Actions

name: Packer
env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  # HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  # HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  HCP_BUCKET_NAME: "mcpaper-java"
  
on:
  push:
    paths:
    - images/**
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches: [ "main" ]
  pull_request:
    paths:
    - images/**
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: images/minecraft-java
    outputs:
      version_fingerprint: ${{ steps.hcp.outputs.version_fingerprint }}
    steps:
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Packer Init
        run: packer init .

      - name: Packer Build - Branches
        if: startsWith(github.ref, 'refs/heads/')
        run: packer build .

      - name: Packer Build - Tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: HCP_PACKER_BUILD_FINGERPRINT=$(date +'%m%d%YT%H%M%S') packer build .

      - name: Get HCP Packer version fingerprint from Packer Manifest
        id: hcp
        run: |
          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
          version_fingerprint=$(echo "$build" | jq -r '.custom_data.version_fingerprint')
          echo "name=version_fingerprint::$version_fingerprint"  >> $GITHUB_OUTPUT
          
  update-hcp-packer-channel:
    name: Update HCP Packer channel
    needs: ["build-artifact"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: images/minecraft-java
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Create and set channel
        working-directory: .github/scripts
        run: |
          channel_name=$( echo ${{github.ref_name}} | sed 's/\./-/g')
          ./create_channel_version.sh $HCP_BUCKET_NAME $channel_name "${{ needs.build-artifact.outputs.version_fingerprint }}"      
